id: IFAC1AA3E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T14:50:19+00:00'
last_modified: '2022-06-07T12:04:51.021760+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15521
  title: གྲངས་རིག་བསམ་བློའི་ཐབས་ལམ་རྣམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9376':
      image_group_id: I1KG15841
      title: Volume 1 of grangs rig bsam blo'i thabs lam rnam bshad/
      total_pages: 236
      order: 1
      base_file: 9376.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
